# Generated by Django 3.0.8 on 2020-08-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200828_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created_on'], 'permissions': [('publish_blog_posts', 'Publisher user - can publish, edit and delete blog posts.')]},
        ),
    ]
